// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ClearChatHistory():Promise<void>;

export function GetChatHistory(arg1:number):Promise<Array<Record<string, string>>>;

export function GetConfig():Promise<config.Config>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function TextToSpeech(arg1:string):Promise<string>;
